### PR TITLE
feat: add support for yarn berry

### PR DESCRIPTION
**Pull request by fargito**
Hello!

This PR adds support for yarn "berry" and its new interface.

What do you think?

Fixes: https://github.com/naugtur/npm-audit-resolver/issues/57

### CODE REVIEW

**Comment by naugtur** [comment]
Great stuff. Sorry I didn't merge it right away. Don't know what I was thinking.

**Comment by fargito** [comment]
Thanks a lot !

**Comment by fargito** [comment]
Can't wait for the release 🚀

**Comment by naugtur** [comment]
@fargito How's it going? need to consult anything?

**Pull request merged**
