### PR TITLE
Updates remind action to snooze for 31 days

### PR DESCRIPTION
**Pull request by stewartduffy**
Still wip.

### CODE REVIEW

**Comment by naugtur** [comment]
I would not be willing to accept this feature, because 24h it's the only choice on purpose. 
It's there to let people transition into secure work culture while working around issues like a new vulnerability on the sprint demo day.

**Comment by adon-at-work** [comment]
@naugtur, how about making the snooze period configurable, or providing more options (like 1d, 3d, 7d, 1m)? think about snoozing a critical vuln vs. a low severity one. If there're no options, we see patterns that people are just completely ignoring it. even more ideally, we can provide one snooze option, where the period depends on severity. let me know your thoughts, we can help with creating a PR

**Comment by stewartduffy** [comment]
I agree with @adon-at-work, and this is the approach we will be taking at work. It would be great if we could get this in this package, but failing that we will need to find a different solution. 24 hours is an unrealistic timeframe. Sometimes there will be vulnerabilities that are out of the developers control (deep dependencies with fixed versions) and in this example this can sometimes take weeks for a patch to be applied.

Giving developers the option to snooze for flexible periods of time is better than forcing them to either fix in 24 hours or ignore forever, I think a lot of devs will end up adding things to the ignore list and forget about it and move on.

**Comment by naugtur** [comment]
The resolver and the check-audit tool work separately, so you can edit the json file manually and set any date in the future.

Postponing was not supposed to be configurable as it's a feature for someone who doesn't have the time to investigate but needs a build to go green now.

In your use case you check and see there's no resolution available at the time and you don't want to introduce protections yourself, I stead decide to run vulnerable code for some more time. 
To me what you're asking is not to configure the postpone feature but to make ignore expire. 

I'm in the process of refactoring internals and changing the format of resolve file. I'll take expiring ignores into account and make sure it's doable.

**Comment by naugtur** [comment]
See the latest commit in refactoring branch, v1 file spec has expiresAt field.
Let's discuss how it could be used and what you'd expect from audit check command in CI

**Comment by adon-at-work** [comment]
thanks @naugtur. i looked at the last commit, which added the `expiresAt` field. 

> Let's discuss how it could be used and what you'd expect from audit check command in CI

so, are you asking for how the developer should interact with the CLIs to supply that `expiresAt` value? is it possible when (1) a developer hits "r" (remind), ask for how long? Alternatively, read a separate policy file that has pre-configured expiry period that depend on severity.

**Comment by naugtur** [comment]
That's what I'm hoping to get from you and other users.
Would it be enough to set a policy in the resolve file for your project and have all ignores expire?
It'd be best IMHO if remind stayed the same, but ignore would either ask for when to expire or default based on settings.

I'd also use the expiry to drop the I fo something has been fixed after a few months.

**Comment by adon-at-work** [comment]
> Would it be enough to set a policy in the resolve file for your project and have all ignores expire?
that will work great! :)

**Comment by adon-at-work** [comment]
ping :)

**Comment by naugtur** [comment]
I'm hoping to look into it next week. Between work and family I currently have like an hour a week for opensource at best. I'll have to spend 6h on a train next week, so that should help ;)

**Comment by naugtur** [comment]
See the refactoring branch. It now has some scaffolding for exposing this functionality. I'll continue the work and  some form of your desired functionality should be there when I'm finished

**Comment by naugtur** [comment]
Just committed an early version yesterday.
You can try it on the branch.

**Comment by adon-at-work** [comment]
Thanks again. :)

I've tried to ignore everything w/1week. Then ran `/check.js` and got ` 😱   Unresolved issues found!`
it looks like it's because of `addStatusToAction()`, which has no logic yet to mark `isMarkedResolved` to `true` for those being ignored during the configured period.

regarding the default `rules.ignoreExpiresInDays`, it seems like it's not configurable depending on severity (yet).

minor UX suggestion. to reproduce, run `/resolve.js`, ignore everything, run `/resolve.js` again. expect something like "^ this was previously ignored until ____ "

**Comment by naugtur** [comment]
valid points, thanks
What's your preference - a setting in resolve file or getting the question on case-by-case basis? How would you use it? Any examples of problems you were facing and wanted to ignore for a while?

**Comment by adon-at-work** [comment]
I think you already exposed a setting `rules` in the resolve file, if you can allow granular choices based on severity as suggested in https://github.com/naugtur/npm-audit-resolver/pull/13#issuecomment-496604235, that'd be awesome!

I'd recommend using the value in the setting, if there's one (no case by case needed).

But if you're unsure, consider providing an extra option. Therefore, one "ignore per rules/policy/setting", and another "ignore" that will ask for how long, just like how it's implemented now.

**Comment by adon-at-work** [comment]
Hi there, I'm pinging to see this can have some love...

**Comment by naugtur** [comment]
I already put the choice in the ignore option for now and I like the idea to use rules for the second option. 
I'll need to release something stable soon so I'm thinking going with the option you need to choose each time is a good enough start.

**Comment by adon-at-work** [comment]
Great. I'm looking forward to the next release. :)

**Comment by naugtur** [comment]
@adon-at-work I published a pre-release of v2. Let me know if/when you try it

**Comment by naugtur** [comment]
Merging the v2 effort now. This can be closed as well

**Pull request closed without merging**
